'use client'

import { BarChart3, Info, RefreshCw } from 'lucide-react'
import { useEffect, useState } from 'react'
import AppShell, { API_BASE, identityForPersona, State, useDemoContext } from '../../components/app-shell'

type Point = { week_start: string; week_end: string; marketing_spend: number; traffic_paid: number; traffic_organic: number; traffic_direct: number; email_sends: number; available_at: string }
export default function CampaignsPage() {
  const { persona, region, category } = useDemoContext()
  const [points, setPoints] = useState<Point[]>([]); const [report, setReport] = useState<{ latest_period?: { week_start: string; week_end: string; available_at: string; coverage: string }; status?: string }>({}); const [error, setError] = useState('')
  useEffect(() => { fetch(`${API_BASE}/api/marketing?region=${encodeURIComponent(region)}&category=${encodeURIComponent(category)}&user_id=${identityForPersona(persona)}`).then(response => response.ok ? response.json() : Promise.reject(new Error('Channel data unavailable'))).then(payload => { setPoints(payload.items ?? []); setReport(payload) }).catch(requestError => setError(requestError.message)) }, [region, category, persona])
  const latest = points.at(-1)
  return <AppShell active="Campaigns" context={`${region} · ${category}`}><div className="page-heading route-heading"><div><span className="eyebrow">Diagnostic channel view</span><h1>Channel and campaign performance</h1><p>The governed dataset has no campaign identifiers. Channel associations are diagnostic, not attribution.</p></div><BarChart3 size={28} /></div>{error ? <div className="alert error">{error}</div> : !points.length ? <State><RefreshCw className="spin" /> No marketing report is available for this scope.</State> : <><section className="summary-strip"><div><strong>{latest?.marketing_spend.toLocaleString('en-IN') ?? '—'}</strong><span>Latest weekly spend</span></div><div><strong>{latest?.traffic_paid.toLocaleString('en-IN') ?? '—'}</strong><span>Paid traffic</span></div><div><strong>{latest?.traffic_organic.toLocaleString('en-IN') ?? '—'}</strong><span>Organic traffic</span></div><div><strong>{latest?.email_sends.toLocaleString('en-IN') ?? '—'}</strong><span>Email sends</span></div></section>{report.latest_period?.coverage === 'PARTIAL' && <div className="alert"><Info size={16} /> Current week is incomplete; values may increase after the next refresh. Reporting period: {report.latest_period.week_start} to {report.latest_period.week_end}. Source available {report.latest_period.available_at}.</div>}<section className="channel-layout"><article className="card detail-card"><span className="eyebrow">Weekly marketing extract</span><h2>Spend and channel signals</h2><div className="spark-bars">{points.slice(-28).map(point => <i key={point.week_start} style={{ height: `${Math.max(8, Math.min(100, point.marketing_spend / Math.max(...points.map(item => item.marketing_spend)) * 100))}%` }} title={`${point.week_start}: ${point.marketing_spend}`} />)}</div><p>Paid {latest?.traffic_paid.toLocaleString('en-IN')} · Organic {latest?.traffic_organic.toLocaleString('en-IN')} · Direct {latest?.traffic_direct.toLocaleString('en-IN')}</p><p className="method-note">Source freshness: {latest?.available_at || 'unavailable'} · grain: weekly.</p></article><article className="card detail-card"><span className="eyebrow"><Info size={14} /> Diagnostic recommendation</span><h2>Use the selected diagnosis action</h2><p>Channel relationships are diagnostic indicators, not attribution or incremental revenue.</p><p>Open the selected investigation to review its engine-generated decision card before changing spend.</p></article></section><section className="card detail-card"><span className="eyebrow">Governance note</span><h2>Campaign-level attribution is not available</h2><p>The governed marketing extract has no campaign identifiers. No campaign names, IDs, or attributed revenue are invented here.</p></section></>}</AppShell>
}
