'use client'

import Link from 'next/link'
import { ArrowLeft, BookOpen, CheckCircle2, ShieldAlert } from 'lucide-react'
import { useEffect, useState } from 'react'
import AppShell, { API_BASE, identityForPersona, State, useDemoContext } from '../../../components/app-shell'
import { contextHref, statusLabel } from '../../../lib/presentation'

type Run = { run_id: string; kpi_id: string; target_date: string; as_of: string; verdict: string; narrative: string; persona: string; segment: { region: string; category: string }; movement_assessment?: { actual_value: number; expected_value: number; delta: number; is_material: boolean }; reconciliation_verdict?: { status: string }; decomposition?: { is_identity_held: boolean; volume_effect: number; price_effect: number; mix_effect: number }; correlational_candidates?: { driver_id: string; max_correlation: number; claim_type: string }[]; confidence?: { status: string; reasons?: string[] }; decision_cards?: { recommendation: string; owner: string; expected_impact: number | null }[] }
type Evidence = { claim: string; source_name: string; source_grain: string; source_freshness: string; row_reference: string; analytical_method: string; claim_type: string; access_classification: string }
export default function DetailPage({ params }: { params: Promise<{ runId: string }> }) {
  const [runId, setRunId] = useState('')
  const { persona, region, category, date, ready } = useDemoContext()
  const [run, setRun] = useState<Run | null>(null); const [evidence, setEvidence] = useState<Evidence[]>([]); const [error, setError] = useState('')
  const [feedbackType, setFeedbackType] = useState('useful'); const [feedbackNote, setFeedbackNote] = useState(''); const [feedbackStatus, setFeedbackStatus] = useState('')
  useEffect(() => { params.then(value => setRunId(value.runId)) }, [params])
  useEffect(() => { if (!runId || !ready) return; const identity = identityForPersona(persona); Promise.all([fetch(`${API_BASE}/api/diagnoses/${runId}?user_id=${identity}`).then(response => response.ok ? response.json() : Promise.reject(new Error('Investigation unavailable'))), fetch(`${API_BASE}/api/diagnoses/${runId}/evidence?user_id=${identity}`).then(response => response.ok ? response.json() : Promise.reject(new Error('Evidence unavailable')))]).then(([payload, evidencePayload]) => { setRun(payload.result ?? payload); setEvidence(evidencePayload.items ?? []) }).catch(requestError => setError(requestError.message)) }, [runId, persona, ready])
  async function submitFeedback() {
    if (!run) return
    const response = await fetch(`${API_BASE}/api/feedback`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ run_id: run.run_id, user_id: identityForPersona(persona), kpi_id: run.kpi_id, feedback_type: feedbackType, comments: feedbackNote, target_type: 'diagnosis', target_id: run.run_id, original_snapshot: { narrative: run.narrative, verdict: run.verdict } }) })
    setFeedbackStatus(response.ok ? 'Feedback submitted for review.' : 'Feedback could not be submitted.')
  }
  if (error) return <AppShell active="Performance"><State><ShieldAlert />{error}</State></AppShell>
  if (!run) return <AppShell active="Performance"><State>Loading investigation…</State></AppShell>
  const movement = run.movement_assessment
  return <AppShell active="Performance" context={`${run.kpi_id} · ${run.target_date} · ${run.segment.region} · ${run.segment.category} · ${run.run_id}`}>
    <Link className="back-link" href={contextHref('/performance', { persona, region: run.segment.region, category: run.segment.category, date: run.target_date })}><ArrowLeft size={15} /> Back to investigations</Link><div className="page-heading route-heading"><div><span className="eyebrow">{run.kpi_id}</span><h1>Investigation detail</h1><p>{run.segment.region} · {run.segment.category} · {run.target_date} · {persona === 'CFO' ? 'Finance review' : 'Marketing review'}</p></div><span className={`status ${movement?.is_material ? 'warn' : 'ok'}`}>{statusLabel(run.verdict)}</span></div>
    <section className="detail-grid"><article className="card detail-card"><span className="eyebrow">What changed</span><h2>{movement?.actual_value.toLocaleString('en-IN')} <small>actual</small></h2><p>Expected {movement?.expected_value.toLocaleString('en-IN')} · Delta {movement?.delta.toLocaleString('en-IN')}</p></article><article className="card detail-card"><span className="eyebrow">Materiality</span><h2>{movement?.is_material ? 'Material movement' : 'Not material'}</h2><p>Reconciliation: {run.reconciliation_verdict?.status ?? 'Not assessed'}</p></article><article className="card detail-card"><span className="eyebrow">Confidence</span><h2>{run.confidence?.status?.replaceAll('_', ' ') ?? 'Not assessed'}</h2><p>{run.confidence?.reasons?.[0] ?? 'Review the evidence before making a causal claim.'}</p></article></section>
    <section className="detail-section"><span className="eyebrow">Evidence-bound narrative</span><h2>{run.narrative}</h2><p className="method-note">Observed movement is distinct from accounting contribution, diagnostic indicators, and observational support.</p></section>
    <section className="detail-grid"><article className="card detail-card"><span className="eyebrow">Accounting contribution</span><h2>{run.decomposition?.is_identity_held ? 'Identity reconciled' : 'Unavailable'}</h2><p>{run.decomposition ? `Volume ${run.decomposition.volume_effect.toFixed(2)} · Rate/price ${run.decomposition.price_effect.toFixed(2)} · Mix ${run.decomposition.mix_effect.toFixed(2)}` : 'No exact bridge is available for this KPI.'}</p></article><article className="card detail-card"><span className="eyebrow">Diagnostic indicators</span>{run.correlational_candidates?.slice(0, 3).map(candidate => <p key={candidate.driver_id}><strong>{candidate.driver_id.replaceAll('_', ' ')}</strong> · correlation {candidate.max_correlation.toFixed(2)} · {candidate.claim_type}</p>) ?? <p>No diagnostic indicator passed the checks.</p>}</article></section>
    <section className="card detail-card"><span className="eyebrow"><BookOpen size={14} /> Evidence lineage</span>{evidence.slice(0, 8).map((item, index) => <div className="evidence-row" key={`${item.source_name}-${index}`}><CheckCircle2 size={15} /><div><strong>{item.source_name}</strong><p>{item.claim_type} · {item.source_grain} · {item.row_reference || 'reference unavailable'}</p><small>{item.analytical_method} · fresh {item.source_freshness} · access {item.access_classification}</small></div></div>)}</section>
    <section className="card detail-card"><span className="eyebrow">Recommended next check</span>{run.decision_cards?.length ? run.decision_cards.map((card, index) => <p key={index}><strong>{card.owner}:</strong> {card.recommendation} <small>Expected impact: {card.expected_impact == null ? 'not estimated' : card.expected_impact}</small></p>) : <p>The engine abstains until more evidence is available.</p>}</section>
    <section className="card detail-card"><span className="eyebrow">Feedback and correction</span><h2>Review this diagnosis</h2><div className="feedback-form"><select value={feedbackType} onChange={event => setFeedbackType(event.target.value)}><option value="accurate">Accurate</option><option value="inaccurate">Inaccurate</option><option value="useful">Useful</option><option value="not_useful">Not useful</option><option value="accept_recommendation">Accept recommendation</option><option value="reject_recommendation">Reject recommendation</option></select><textarea value={feedbackNote} onChange={event => setFeedbackNote(event.target.value)} placeholder="Optional correction or note" aria-label="Feedback note" /><button className="run-button" onClick={() => void submitFeedback()}>Submit feedback</button></div>{feedbackStatus && <p>{feedbackStatus}</p>}</section>
  </AppShell>
}
